name: unilab
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0
  multi_split_view: ^3.1.0
  flutter_code_editor: ^0.3.5
  google_fonts: ^6.2.1
  file_picker: ^8.1.7
  path_provider: ^2.1.5
  http: ^1.2.2
  ffi: ^2.1.3
  flutter_highlight: ^0.7.0
  shared_preferences: ^2.5.2
  path: ^1.9.1
  highlight: ^0.7.0

  # UI/UX Redesign Dependencies
  fl_chart: ^1.2.0
  context_menus: ^2.0.0+1
  intl: ^0.20.2
  uuid: ^4.5.3
  window_manager: ^0.5.1
  desktop_drop: ^0.7.1
  fuzzy: ^0.5.1
  pluto_grid: ^8.1.0
  undo: ^1.2.3
  watcher: ^1.2.1
  flutter_fancy_tree_view: ^1.6.0
  flutter_awesome_context_menu: ^0.1.1
  lucide_icons_flutter: ^3.1.14+2
  flex_color_picker: ^3.6.0
  pdfrx: ^1.0.86
  xterm: ^4.0.0
  flutter_pty: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  riverpod_generator: ^2.3.0

flutter:
  uses-material-design: true
